# Configuration for the Black Code Formatter
[tool.black]
line-length = 99

# Configuration for the isort Import Sorter
[tool.isort]
profile = "black"
line_length = 99

# Configuration for Pytest
[tool.pytest.ini_options]
pythonpath = ["./src"]
